import "./globals.css";
import Provider from "@/components/provider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-20 bg-slate-100">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
